create extension if not exists pgcrypto;

create table if not exists tenants (
    id uuid primary key,
    name varchar(200) not null,
    created_at_utc timestamptz not null default now()
);

create table if not exists messages (
    id uuid primary key,
    tenant_id uuid not null references tenants(id),
    channel varchar(30) not null,
    recipient varchar(320) not null,
    subject varchar(500),
    body text not null,
    status varchar(30) not null,
    provider_message_id varchar(200),
    error text,
    created_at_utc timestamptz not null default now(),
    updated_at_utc timestamptz,
    sent_at timestamptz
);

create index if not exists ix_messages_tenant_id_created_at
    on messages (tenant_id, created_at_utc desc);

create index if not exists ix_messages_queue
    on messages (status, created_at_utc);

create table if not exists message_events (
    id bigint generated by default as identity primary key,
    message_id uuid not null references messages(id),
    event_type varchar(50) not null,
    provider_payload text,
    created_at_utc timestamptz not null default now()
);

insert into tenants (id, name)
values ('00000000-0000-0000-0000-000000000001', 'TriSend MVP')
on conflict (id) do nothing;
